### ISSUE TITLE
Testing Python library - Is there a test VASP?

### ISSUE THREAD

**Issue by trbouma** [uma-universal-money-address/uma-python-sdk#8]
Not an issue, but just wanted to let you know I am implementing using the Python library and am implementing the uma protocol. I'd be keen to know if there is a test vasp I can test with. Once my implementation is ready, I am happy to enable it for testing as well.

**Comment by jklein24** [comment]
Hey @trbouma! I have my own little demo VASP on mainnet that you can test against when you're ready and I'm happy to move around small amounts of sats to help you verify things.

**Comment by jklein24** [comment]
Ah I see you managed to contact over telegram, so we can continue the conversation there. Sorry I missed this github issue!
